NumPy Arrays - 
Learn About Markdown

In [3]:
import numpy as np 

In [1]:
my_list = [1,2,3]

In [5]:
arr = np.array(my_list) ### cast a python list into an array 

In [6]:
arr

array([1, 2, 3])

In [8]:
###if you want to get a 2d array or matrix
###cast a list of lists 

In [9]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
np.array(my_mat) ###this will return a list of lists 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
###continue at 2 mins 

In [15]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [21]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [23]:
np.ones((4,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [32]:
np.linspace(0,5,10) #start end and spacing 

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [33]:
#continue at 7mins

In [34]:
##identity matrix

np.eye(6) ##they must be square

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [35]:
###numpy can generate random numbers

In [36]:
np.random.rand()

0.6121109985225427

In [37]:
np.random.rand(5)

array([ 0.81814838,  0.32872847,  0.82831848,  0.69177891,  0.46759106])

In [39]:
np.random.rand(5,5) # random number from 0 to 1

array([[ 0.47215188,  0.76181403,  0.13425078,  0.06866943,  0.86358727],
       [ 0.95374214,  0.12574349,  0.51533076,  0.97892926,  0.27005547],
       [ 0.25362433,  0.89531767,  0.62879124,  0.57018244,  0.23871902],
       [ 0.42003262,  0.92438831,  0.23522448,  0.39595326,  0.20256253],
       [ 0.6094455 ,  0.88302711,  0.0368526 ,  0.77508047,  0.02470758]])

In [44]:
np.random.randn() 
#show a normal distribution curve 
#gaussian distribution 
#standard normal distribution centred around zero

-1.9919854368896626

In [46]:
np.random.randn(4)

array([ 2.35201845,  0.18961272, -1.00786993,  0.21991194])

In [48]:
np.random.randn(4,4)

array([[ 1.19526135,  0.18662472, -0.97929076, -0.09074702],
       [ 1.517668  , -0.39279422,  1.29543424, -0.27516374],
       [ 0.6150978 , -0.86421973, -0.1958895 ,  0.30908389],
       [-1.45669153, -1.79681492, -0.25499377,  0.27515355]])

In [49]:
np.random.randint(0,4)

1

In [50]:
np.random.randint(0,40,10) ###not including the last number 

array([ 7,  4, 22,  5, 36,  4, 19, 17, 11, 25])

In [51]:
arr= np.arange(25)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
ranarr = np.random.randint(0,50,10)

In [56]:
ranarr

array([17, 28, 34, 21, 41, 11, 18, 38, 34, 38])

In [57]:
##Continue at 11.40

In [58]:
arr.reshape(5,5) # must equal the number ofelements you have

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
ranarr

array([17, 28, 34, 21, 41, 11, 18, 38, 34, 38])

In [61]:
ranarr.max()

41

In [63]:
ranarr.min()

11

In [64]:
ranarr.argmax() #returns the index of the max location 

4

In [66]:
ranarr.argmin() #returns the index of the min location

5

In [67]:
arr.shape

(25,)

In [69]:
arr2 = np.random.rand(5,5)

In [70]:
arr2 = arr2.reshape(5,5)

In [71]:
arr2.shape

(5, 5)

In [72]:
arr.dtype

dtype('int32')

In [76]:
###if you dont want to type np.random before the function you want do this function
from numpy.random import randint

In [79]:
randint(2,10)

6

In [80]:
###summary of class 
###create numpy arrays 
###array, arrange 
###rand randn randint

In [82]:
#lecture 19 array indexing 

##select elements in a numpy array 

In [83]:
arr = np.arange(0,11)

In [84]:
#use brackets and slice notation to do this 

In [85]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [86]:
arr[:4]

array([0, 1, 2, 3])

In [87]:
arr[8]

8

In [88]:
arr[1:5]

array([1, 2, 3, 4])

In [89]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [90]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [91]:
###this is the same notation that you would use in a python list 

In [92]:
####arrays are different to lists because they have the ability to broadcast 

In [93]:
arr[0:5] = 100

In [94]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [95]:
####broadcasting means changing the values of the slection you give it 

In [98]:
arr = np.arange(0,11)

In [99]:
slice_of_arr = arr[0:6]

In [100]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [101]:
slice_of_arr[:] = 99

In [102]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [103]:
####what it it saying is that it changes the original array

In [104]:
###everything always is a reference to the initial array 

In [105]:
##if you want a copy and not a reference do this

In [106]:
arr_copy = arr.copy()

In [107]:
arr_copy[:]=100

In [108]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [109]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [110]:
##########lets do a 2d array

In [112]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [113]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [114]:
arr_2d[0][0]

5

In [119]:
arr_2d[:][2]

array([35, 40, 45])

In [121]:
arr_2d[0][:]  #this always gets the row

array([ 5, 10, 15])

In [122]:
####how do you get the column?

In [123]:
arr_2d[0]

array([ 5, 10, 15])

In [125]:
arr_2d[1][1]

5

In [126]:
#####dont use the above...stupid why they show you this first and for longer 

In [127]:
arr_2d[2,1]

40

In [129]:
####grabbing chunks 

###need to spend more time on this 
arr_2d[:2,1:] #everything up to row 2, column 1 onwards

array([[10, 15],
       [25, 30]])

In [130]:
##continue at 11 mins

In [133]:
###to get a column 
arr_2d[:, 1:2] ###column 1 not including 2

array([[10],
       [25],
       [40]])

In [134]:
arr_2d[:2] #rows up to but not including 2

array([[ 5, 10, 15],
       [20, 25, 30]])

In [135]:
arr_2d[2]

array([35, 40, 45])

In [136]:
####conditional selection 

In [137]:
##coditional selection is much more common 

In [139]:
arr = np.arange(1,11)

In [140]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [142]:
bool_arr = arr > 5

In [143]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [145]:
arr[bool_arr] ###this is so useful as it only shows true statements

array([ 6,  7,  8,  9, 10])

In [146]:
###this is a simple way to do it 
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [147]:
arr[arr<3]

array([1, 2])

In [148]:
####exercise for myself

In [149]:
arr_2d = np.arange(50).reshape(5,10)

In [150]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [154]:
#grab 13 and 14 
arr_2d[1:2, 3:5]

#grab 23 and 24
arr_2d[2:3, 3:5]

#grab them both together
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [155]:
#conditional operations using comparison operators are used more 

In [156]:
#####################lecture 20#################

In [157]:
###numpy operations 

In [158]:
#array with array operations
#array with scalar operations
#universal array functions 

In [159]:
arr = np.arange(0,11)

In [160]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [162]:
arr2 = arr + arr

In [163]:
arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [164]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [165]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [166]:
arr  +100 ###adds the number to every element in the array 

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [167]:
arr* 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [168]:
arr/ 100

array([ 0.  ,  0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,
        0.09,  0.1 ])

In [169]:
1/0

ZeroDivisionError: division by zero

In [170]:
arr/arr  ###this will run but with an error

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [171]:
1/0

ZeroDivisionError: division by zero

In [172]:
1/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [173]:
###there are lots of errors when it comes to dividing by zero 

In [175]:
arr**4 ###this is like when you do to the power of 

array([    0,     1,    16,    81,   256,   625,  1296,  2401,  4096,
        6561, 10000], dtype=int32)

In [176]:
########################

In [177]:
#if you want to do the square root of everynumber across the array 
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [179]:
###if you want to do the exponential 
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [180]:
np.max(arr)

10

In [181]:
np.min(arr)

0

In [182]:
arr.max()

10

In [183]:
arr.min()

0

In [185]:
np.log(arr) ### learn more abou this stuff...really simple maths 

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])

In [186]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [187]:
######you can find a list of all the universal array functions 

In [188]:
"https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html#available-ufuncs"

'https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html#available-ufuncs'

In [189]:
##########lecture 21####

In [190]:
#exercise overview

In [191]:
###how to approach the section 

In [192]:
#follow the book and fill in the blanks 